image: eclipse-temurin:17-jdk

stages:
  - validate
  - build
  - distribute

include:
  - local: '.gitlab/variables.yml'
  - local: '.gitlab/validate.yml'
  - local: '.gitlab/build.yml'
  - local: '.gitlab/distribute.yml'

cache:
  key: android-sdk-cache
  paths:
    - android-sdk-root/
    - .gradle/

before_script:
  - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
  - chmod +x ./gradlew